version: '2'
services:
    lms-app:
        image: lms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://lms-mysql:3306/lms?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    lms-mysql:
        extends:
            file: mysql.yml
            service: lms-mysql
